inputSpec: https://schematic-openapi-da6da39.s3.amazonaws.com/latest.yml
generatorName: typescript-fetch
outputDir: ./src/api/
additionalProperties:
  composerPackageName: prependFormOrBodyParameters
  stringEnums: true
gitHost: github.com
gitUserId: SchematicHQ
gitRepoId: schematic-typescript-node
