generatorName: typescript-fetch
inputSpec: https://schematic-openapi-da6da39.s3.amazonaws.com/latest.yml
outputDir: src/api
enablePostProcessFile: true
additionalProperties:
  prependFormOrBodyParameters: true
gitHost: github.com
gitUserId: SchematicHQ
gitRepoId: schematic-typescript-node
