generatorName: typescript-fetch
inputSpec: /Users/mango/development/schematic/schematic-api/docs/openapi.yaml
outputDir: src/api
templateDir: templates
enablePostProcessFile: true
additionalProperties:
  prependFormOrBodyParameters: true
gitHost: github.com
gitUserId: SchematicHQ
gitRepoId: schematic-typescript-node
