/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The updated resource
 * @export
 * @interface ApiKeyResponseData
 */
export interface ApiKeyResponseData {
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponseData
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponseData
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponseData
     */
    environmentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponseData
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponseData
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponseData
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKeyResponseData
     */
    scopes: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponseData
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ApiKeyResponseData interface.
 */
export function instanceOfApiKeyResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "scopes" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ApiKeyResponseDataFromJSON(json: any): ApiKeyResponseData {
    return ApiKeyResponseDataFromJSONTyped(json, false);
}

export function ApiKeyResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'id': json['id'],
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : (json['last_used_at'] === null ? null : new Date(json['last_used_at'])),
        'name': json['name'],
        'scopes': json['scopes'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ApiKeyResponseDataToJSON(value?: ApiKeyResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.createdAt.toISOString()),
        'description': value.description,
        'environment_id': value.environmentId,
        'id': value.id,
        'last_used_at': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt === null ? null : value.lastUsedAt.toISOString()),
        'name': value.name,
        'scopes': value.scopes,
        'updated_at': (value.updatedAt.toISOString()),
    };
}

