/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CountEventTypes200ResponseData } from './CountEventTypes200ResponseData';
import {
    CountEventTypes200ResponseDataFromJSON,
    CountEventTypes200ResponseDataFromJSONTyped,
    CountEventTypes200ResponseDataToJSON,
} from './CountEventTypes200ResponseData';
import type { ListEventTypes200ResponseParams } from './ListEventTypes200ResponseParams';
import {
    ListEventTypes200ResponseParamsFromJSON,
    ListEventTypes200ResponseParamsFromJSONTyped,
    ListEventTypes200ResponseParamsToJSON,
} from './ListEventTypes200ResponseParams';

/**
 * 
 * @export
 * @interface CountEventTypes200Response
 */
export interface CountEventTypes200Response {
    /**
     * 
     * @type {CountEventTypes200ResponseData}
     * @memberof CountEventTypes200Response
     */
    data?: CountEventTypes200ResponseData;
    /**
     * 
     * @type {ListEventTypes200ResponseParams}
     * @memberof CountEventTypes200Response
     */
    params?: ListEventTypes200ResponseParams;
}

/**
 * Check if a given object implements the CountEventTypes200Response interface.
 */
export function instanceOfCountEventTypes200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CountEventTypes200ResponseFromJSON(json: any): CountEventTypes200Response {
    return CountEventTypes200ResponseFromJSONTyped(json, false);
}

export function CountEventTypes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountEventTypes200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CountEventTypes200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : ListEventTypes200ResponseParamsFromJSON(json['params']),
    };
}

export function CountEventTypes200ResponseToJSON(value?: CountEventTypes200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CountEventTypes200ResponseDataToJSON(value.data),
        'params': ListEventTypes200ResponseParamsToJSON(value.params),
    };
}

