/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CountEventsCount200ResponseData } from './CountEventsCount200ResponseData';
import {
    CountEventsCount200ResponseDataFromJSON,
    CountEventsCount200ResponseDataFromJSONTyped,
    CountEventsCount200ResponseDataToJSON,
} from './CountEventsCount200ResponseData';
import type { ListEvents200ResponseParams } from './ListEvents200ResponseParams';
import {
    ListEvents200ResponseParamsFromJSON,
    ListEvents200ResponseParamsFromJSONTyped,
    ListEvents200ResponseParamsToJSON,
} from './ListEvents200ResponseParams';

/**
 * 
 * @export
 * @interface CountEventsCount200Response
 */
export interface CountEventsCount200Response {
    /**
     * 
     * @type {CountEventsCount200ResponseData}
     * @memberof CountEventsCount200Response
     */
    data?: CountEventsCount200ResponseData;
    /**
     * 
     * @type {ListEvents200ResponseParams}
     * @memberof CountEventsCount200Response
     */
    params?: ListEvents200ResponseParams;
}

/**
 * Check if a given object implements the CountEventsCount200Response interface.
 */
export function instanceOfCountEventsCount200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CountEventsCount200ResponseFromJSON(json: any): CountEventsCount200Response {
    return CountEventsCount200ResponseFromJSONTyped(json, false);
}

export function CountEventsCount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountEventsCount200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CountEventsCount200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : ListEvents200ResponseParamsFromJSON(json['params']),
    };
}

export function CountEventsCount200ResponseToJSON(value?: CountEventsCount200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CountEventsCount200ResponseDataToJSON(value.data),
        'params': ListEvents200ResponseParamsToJSON(value.params),
    };
}

