/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The returned resource
 * @export
 * @interface CountEventsCount200ResponseData
 */
export interface CountEventsCount200ResponseData {
    /**
     * The number of resources
     * @type {number}
     * @memberof CountEventsCount200ResponseData
     */
    count?: number;
}

/**
 * Check if a given object implements the CountEventsCount200ResponseData interface.
 */
export function instanceOfCountEventsCount200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CountEventsCount200ResponseDataFromJSON(json: any): CountEventsCount200ResponseData {
    return CountEventsCount200ResponseDataFromJSONTyped(json, false);
}

export function CountEventsCount200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountEventsCount200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function CountEventsCount200ResponseDataToJSON(value?: CountEventsCount200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

