/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateCompanyMembership201ResponseData } from './CreateCompanyMembership201ResponseData';
import {
    CreateCompanyMembership201ResponseDataFromJSON,
    CreateCompanyMembership201ResponseDataFromJSONTyped,
    CreateCompanyMembership201ResponseDataToJSON,
} from './CreateCompanyMembership201ResponseData';

/**
 * 
 * @export
 * @interface CreateCompanyMembership201Response
 */
export interface CreateCompanyMembership201Response {
    /**
     * 
     * @type {CreateCompanyMembership201ResponseData}
     * @memberof CreateCompanyMembership201Response
     */
    data?: CreateCompanyMembership201ResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof CreateCompanyMembership201Response
     */
    params?: object;
}

/**
 * Check if a given object implements the CreateCompanyMembership201Response interface.
 */
export function instanceOfCreateCompanyMembership201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateCompanyMembership201ResponseFromJSON(json: any): CreateCompanyMembership201Response {
    return CreateCompanyMembership201ResponseFromJSONTyped(json, false);
}

export function CreateCompanyMembership201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompanyMembership201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CreateCompanyMembership201ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function CreateCompanyMembership201ResponseToJSON(value?: CreateCompanyMembership201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateCompanyMembership201ResponseDataToJSON(value.data),
        'params': value.params,
    };
}

