/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeaturesRequestFlag
 */
export interface CreateFeaturesRequestFlag {
    /**
     * 
     * @type {string}
     * @memberof CreateFeaturesRequestFlag
     */
    flagType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeaturesRequestFlag
     */
    key?: string;
}

/**
 * Check if a given object implements the CreateFeaturesRequestFlag interface.
 */
export function instanceOfCreateFeaturesRequestFlag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFeaturesRequestFlagFromJSON(json: any): CreateFeaturesRequestFlag {
    return CreateFeaturesRequestFlagFromJSONTyped(json, false);
}

export function CreateFeaturesRequestFlagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeaturesRequestFlag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flagType': !exists(json, 'flag_type') ? undefined : json['flag_type'],
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function CreateFeaturesRequestFlagToJSON(value?: CreateFeaturesRequestFlag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flag_type': value.flagType,
        'key': value.key,
    };
}

