/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnvironmentRequest
 */
export interface CreateEnvironmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentRequest
     */
    environmentType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEnvironmentRequest
     */
    skipWebhooks?: boolean;
}

/**
 * Check if a given object implements the CreateEnvironmentRequest interface.
 */
export function instanceOfCreateEnvironmentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateEnvironmentRequestFromJSON(json: any): CreateEnvironmentRequest {
    return CreateEnvironmentRequestFromJSONTyped(json, false);
}

export function CreateEnvironmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnvironmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'environmentType': !exists(json, 'environment_type') ? undefined : json['environment_type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'skipWebhooks': !exists(json, 'skip_webhooks') ? undefined : json['skip_webhooks'],
    };
}

export function CreateEnvironmentRequestToJSON(value?: CreateEnvironmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'environment_type': value.environmentType,
        'name': value.name,
        'skip_webhooks': value.skipWebhooks,
    };
}

