/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeature200ResponseDataFlagsInnerRulesInner } from './CreateFeature200ResponseDataFlagsInnerRulesInner';
import {
    CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSON,
    CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSONTyped,
    CreateFeature200ResponseDataFlagsInnerRulesInnerToJSON,
} from './CreateFeature200ResponseDataFlagsInnerRulesInner';

/**
 * The returned resource
 * @export
 * @interface CreateFlag200ResponseData
 */
export interface CreateFlag200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateFlag200ResponseData
     */
    defaultValue?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    featureId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    flagType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    name?: string;
    /**
     * 
     * @type {Array<CreateFeature200ResponseDataFlagsInnerRulesInner>}
     * @memberof CreateFlag200ResponseData
     */
    rules?: Array<CreateFeature200ResponseDataFlagsInnerRulesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateFlag200ResponseData
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the CreateFlag200ResponseData interface.
 */
export function instanceOfCreateFlag200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFlag200ResponseDataFromJSON(json: any): CreateFlag200ResponseData {
    return CreateFlag200ResponseDataFromJSONTyped(json, false);
}

export function CreateFlag200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFlag200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'defaultValue': !exists(json, 'default_value') ? undefined : json['default_value'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'flagType': !exists(json, 'flag_type') ? undefined : json['flag_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'rules': !exists(json, 'rules') ? undefined : ((json['rules'] as Array<any>).map(CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSON)),
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function CreateFlag200ResponseDataToJSON(value?: CreateFlag200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'default_value': value.defaultValue,
        'description': value.description,
        'feature_id': value.featureId,
        'flag_type': value.flagType,
        'id': value.id,
        'key': value.key,
        'name': value.name,
        'rules': value.rules === undefined ? undefined : ((value.rules as Array<any>).map(CreateFeature200ResponseDataFlagsInnerRulesInnerToJSON)),
        'updated_at': value.updatedAt,
    };
}

