/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeatureRequestFlagRulesInnerConditionsInner } from './CreateFeatureRequestFlagRulesInnerConditionsInner';
import {
    CreateFeatureRequestFlagRulesInnerConditionsInnerFromJSON,
    CreateFeatureRequestFlagRulesInnerConditionsInnerFromJSONTyped,
    CreateFeatureRequestFlagRulesInnerConditionsInnerToJSON,
} from './CreateFeatureRequestFlagRulesInnerConditionsInner';

/**
 * 
 * @export
 * @interface CreateFeatureRequestFlagRulesInner
 */
export interface CreateFeatureRequestFlagRulesInner {
    /**
     * 
     * @type {Array<CreateFeatureRequestFlagRulesInnerConditionsInner>}
     * @memberof CreateFeatureRequestFlagRulesInner
     */
    conditions: Array<CreateFeatureRequestFlagRulesInnerConditionsInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateFeatureRequestFlagRulesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeatureRequestFlagRulesInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateFeatureRequestFlagRulesInner
     */
    priority: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateFeatureRequestFlagRulesInner
     */
    value: boolean;
}

/**
 * Check if a given object implements the CreateFeatureRequestFlagRulesInner interface.
 */
export function instanceOfCreateFeatureRequestFlagRulesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "conditions" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "priority" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CreateFeatureRequestFlagRulesInnerFromJSON(json: any): CreateFeatureRequestFlagRulesInner {
    return CreateFeatureRequestFlagRulesInnerFromJSONTyped(json, false);
}

export function CreateFeatureRequestFlagRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeatureRequestFlagRulesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': ((json['conditions'] as Array<any>).map(CreateFeatureRequestFlagRulesInnerConditionsInnerFromJSON)),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'priority': json['priority'],
        'value': json['value'],
    };
}

export function CreateFeatureRequestFlagRulesInnerToJSON(value?: CreateFeatureRequestFlagRulesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': ((value.conditions as Array<any>).map(CreateFeatureRequestFlagRulesInnerConditionsInnerToJSON)),
        'id': value.id,
        'name': value.name,
        'priority': value.priority,
        'value': value.value,
    };
}

