/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompanyMembershipDetailResponseData } from './CompanyMembershipDetailResponseData';
import {
    CompanyMembershipDetailResponseDataFromJSON,
    CompanyMembershipDetailResponseDataFromJSONTyped,
    CompanyMembershipDetailResponseDataToJSON,
} from './CompanyMembershipDetailResponseData';

/**
 * 
 * @export
 * @interface CreateCompanyMembershipResponse
 */
export interface CreateCompanyMembershipResponse {
    /**
     * 
     * @type {CompanyMembershipDetailResponseData}
     * @memberof CreateCompanyMembershipResponse
     */
    data: CompanyMembershipDetailResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof CreateCompanyMembershipResponse
     */
    params: object;
}

/**
 * Check if a given object implements the CreateCompanyMembershipResponse interface.
 */
export function instanceOfCreateCompanyMembershipResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function CreateCompanyMembershipResponseFromJSON(json: any): CreateCompanyMembershipResponse {
    return CreateCompanyMembershipResponseFromJSONTyped(json, false);
}

export function CreateCompanyMembershipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompanyMembershipResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CompanyMembershipDetailResponseDataFromJSON(json['data']),
        'params': json['params'],
    };
}

export function CreateCompanyMembershipResponseToJSON(value?: CreateCompanyMembershipResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CompanyMembershipDetailResponseDataToJSON(value.data),
        'params': value.params,
    };
}

