/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeature201ResponseDataFlagsInner } from './CreateFeature201ResponseDataFlagsInner';
import {
    CreateFeature201ResponseDataFlagsInnerFromJSON,
    CreateFeature201ResponseDataFlagsInnerFromJSONTyped,
    CreateFeature201ResponseDataFlagsInnerToJSON,
} from './CreateFeature201ResponseDataFlagsInner';
import type { ListEventTypes200ResponseDataInner } from './ListEventTypes200ResponseDataInner';
import {
    ListEventTypes200ResponseDataInnerFromJSON,
    ListEventTypes200ResponseDataInnerFromJSONTyped,
    ListEventTypes200ResponseDataInnerToJSON,
} from './ListEventTypes200ResponseDataInner';

/**
 * The returned resource
 * @export
 * @interface CreateFeature201ResponseData
 */
export interface CreateFeature201ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    eventSubtype?: string;
    /**
     * 
     * @type {ListEventTypes200ResponseDataInner}
     * @memberof CreateFeature201ResponseData
     */
    eventSummary?: ListEventTypes200ResponseDataInner;
    /**
     * 
     * @type {Array<CreateFeature201ResponseDataFlagsInner>}
     * @memberof CreateFeature201ResponseData
     */
    flags: Array<CreateFeature201ResponseDataFlagsInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    lifecyclePhase?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeature201ResponseData
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CreateFeature201ResponseData interface.
 */
export function instanceOfCreateFeature201ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "flags" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function CreateFeature201ResponseDataFromJSON(json: any): CreateFeature201ResponseData {
    return CreateFeature201ResponseDataFromJSONTyped(json, false);
}

export function CreateFeature201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeature201ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'description': json['description'],
        'eventSubtype': !exists(json, 'event_subtype') ? undefined : json['event_subtype'],
        'eventSummary': !exists(json, 'event_summary') ? undefined : ListEventTypes200ResponseDataInnerFromJSON(json['event_summary']),
        'flags': ((json['flags'] as Array<any>).map(CreateFeature201ResponseDataFlagsInnerFromJSON)),
        'id': json['id'],
        'lifecyclePhase': !exists(json, 'lifecycle_phase') ? undefined : json['lifecycle_phase'],
        'name': json['name'],
        'updatedAt': json['updated_at'],
    };
}

export function CreateFeature201ResponseDataToJSON(value?: CreateFeature201ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'description': value.description,
        'event_subtype': value.eventSubtype,
        'event_summary': ListEventTypes200ResponseDataInnerToJSON(value.eventSummary),
        'flags': ((value.flags as Array<any>).map(CreateFeature201ResponseDataFlagsInnerToJSON)),
        'id': value.id,
        'lifecycle_phase': value.lifecyclePhase,
        'name': value.name,
        'updated_at': value.updatedAt,
    };
}

