/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The created resource
 * @export
 * @interface CreateEvent201ResponseData
 */
export interface CreateEvent201ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    apiKey: string;
    /**
     * 
     * @type {object}
     * @memberof CreateEvent201ResponseData
     */
    body: object;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    capturedAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    enrichedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    environmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    featureId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    loadedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    processedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    processingStatus: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    sentAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    subtype?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvent201ResponseData
     */
    userId?: string;
}

/**
 * Check if a given object implements the CreateEvent201ResponseData interface.
 */
export function instanceOfCreateEvent201ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "apiKey" in value;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "capturedAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "processingStatus" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function CreateEvent201ResponseDataFromJSON(json: any): CreateEvent201ResponseData {
    return CreateEvent201ResponseDataFromJSONTyped(json, false);
}

export function CreateEvent201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEvent201ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
        'body': json['body'],
        'capturedAt': json['captured_at'],
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'enrichedAt': !exists(json, 'enriched_at') ? undefined : json['enriched_at'],
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'id': json['id'],
        'loadedAt': !exists(json, 'loaded_at') ? undefined : json['loaded_at'],
        'processedAt': !exists(json, 'processed_at') ? undefined : json['processed_at'],
        'processingStatus': json['processing_status'],
        'sentAt': !exists(json, 'sent_at') ? undefined : json['sent_at'],
        'subtype': !exists(json, 'subtype') ? undefined : json['subtype'],
        'type': json['type'],
        'updatedAt': json['updated_at'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function CreateEvent201ResponseDataToJSON(value?: CreateEvent201ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api_key': value.apiKey,
        'body': value.body,
        'captured_at': value.capturedAt,
        'company_id': value.companyId,
        'enriched_at': value.enrichedAt,
        'environment_id': value.environmentId,
        'feature_id': value.featureId,
        'id': value.id,
        'loaded_at': value.loadedAt,
        'processed_at': value.processedAt,
        'processing_status': value.processingStatus,
        'sent_at': value.sentAt,
        'subtype': value.subtype,
        'type': value.type,
        'updated_at': value.updatedAt,
        'user_id': value.userId,
    };
}

