/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCompanyMembershipRequest
 */
export interface CreateCompanyMembershipRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyMembershipRequest
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyMembershipRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the CreateCompanyMembershipRequest interface.
 */
export function instanceOfCreateCompanyMembershipRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateCompanyMembershipRequestFromJSON(json: any): CreateCompanyMembershipRequest {
    return CreateCompanyMembershipRequestFromJSONTyped(json, false);
}

export function CreateCompanyMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompanyMembershipRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function CreateCompanyMembershipRequestToJSON(value?: CreateCompanyMembershipRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'user_id': value.userId,
    };
}

