/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateCompany200ResponseData } from './CreateCompany200ResponseData';
import {
    CreateCompany200ResponseDataFromJSON,
    CreateCompany200ResponseDataFromJSONTyped,
    CreateCompany200ResponseDataToJSON,
} from './CreateCompany200ResponseData';

/**
 * 
 * @export
 * @interface CreateCompany200Response
 */
export interface CreateCompany200Response {
    /**
     * 
     * @type {CreateCompany200ResponseData}
     * @memberof CreateCompany200Response
     */
    data?: CreateCompany200ResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof CreateCompany200Response
     */
    params?: object;
}

/**
 * Check if a given object implements the CreateCompany200Response interface.
 */
export function instanceOfCreateCompany200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateCompany200ResponseFromJSON(json: any): CreateCompany200Response {
    return CreateCompany200ResponseFromJSONTyped(json, false);
}

export function CreateCompany200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompany200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CreateCompany200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function CreateCompany200ResponseToJSON(value?: CreateCompany200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateCompany200ResponseDataToJSON(value.data),
        'params': value.params,
    };
}

