/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInner } from './CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInner';
import {
    CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInnerFromJSON,
    CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInnerFromJSONTyped,
    CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInnerToJSON,
} from './CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInner';
import type { CreateFeature200ResponseDataFlagsInnerRulesInnerRule } from './CreateFeature200ResponseDataFlagsInnerRulesInnerRule';
import {
    CreateFeature200ResponseDataFlagsInnerRulesInnerRuleFromJSON,
    CreateFeature200ResponseDataFlagsInnerRulesInnerRuleFromJSONTyped,
    CreateFeature200ResponseDataFlagsInnerRulesInnerRuleToJSON,
} from './CreateFeature200ResponseDataFlagsInnerRulesInnerRule';

/**
 * 
 * @export
 * @interface CreateFeature200ResponseDataFlagsInnerRulesInner
 */
export interface CreateFeature200ResponseDataFlagsInnerRulesInner {
    /**
     * 
     * @type {Array<CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInner>}
     * @memberof CreateFeature200ResponseDataFlagsInnerRulesInner
     */
    conditions?: Array<CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInner>;
    /**
     * 
     * @type {CreateFeature200ResponseDataFlagsInnerRulesInnerRule}
     * @memberof CreateFeature200ResponseDataFlagsInnerRulesInner
     */
    rule?: CreateFeature200ResponseDataFlagsInnerRulesInnerRule;
}

/**
 * Check if a given object implements the CreateFeature200ResponseDataFlagsInnerRulesInner interface.
 */
export function instanceOfCreateFeature200ResponseDataFlagsInnerRulesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSON(json: any): CreateFeature200ResponseDataFlagsInnerRulesInner {
    return CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSONTyped(json, false);
}

export function CreateFeature200ResponseDataFlagsInnerRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeature200ResponseDataFlagsInnerRulesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': !exists(json, 'conditions') ? undefined : ((json['conditions'] as Array<any>).map(CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInnerFromJSON)),
        'rule': !exists(json, 'rule') ? undefined : CreateFeature200ResponseDataFlagsInnerRulesInnerRuleFromJSON(json['rule']),
    };
}

export function CreateFeature200ResponseDataFlagsInnerRulesInnerToJSON(value?: CreateFeature200ResponseDataFlagsInnerRulesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': value.conditions === undefined ? undefined : ((value.conditions as Array<any>).map(CreateFeature200ResponseDataFlagsInnerRulesInnerConditionsInnerToJSON)),
        'rule': CreateFeature200ResponseDataFlagsInnerRulesInnerRuleToJSON(value.rule),
    };
}

