/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventsCountGet200ResponseDataInner
 */
export interface EventsCountGet200ResponseDataInner {
    /**
     * The number of resources
     * @type {number}
     * @memberof EventsCountGet200ResponseDataInner
     */
    count?: number;
}

/**
 * Check if a given object implements the EventsCountGet200ResponseDataInner interface.
 */
export function instanceOfEventsCountGet200ResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventsCountGet200ResponseDataInnerFromJSON(json: any): EventsCountGet200ResponseDataInner {
    return EventsCountGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function EventsCountGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsCountGet200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function EventsCountGet200ResponseDataInnerToJSON(value?: EventsCountGet200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

