/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomersGet200ResponseParams } from './CustomersGet200ResponseParams';
import {
    CustomersGet200ResponseParamsFromJSON,
    CustomersGet200ResponseParamsFromJSONTyped,
    CustomersGet200ResponseParamsToJSON,
} from './CustomersGet200ResponseParams';
import type { FeaturesGet200ResponseData } from './FeaturesGet200ResponseData';
import {
    FeaturesGet200ResponseDataFromJSON,
    FeaturesGet200ResponseDataFromJSONTyped,
    FeaturesGet200ResponseDataToJSON,
} from './FeaturesGet200ResponseData';

/**
 * 
 * @export
 * @interface FeaturesGet200Response
 */
export interface FeaturesGet200Response {
    /**
     * 
     * @type {FeaturesGet200ResponseData}
     * @memberof FeaturesGet200Response
     */
    data?: FeaturesGet200ResponseData;
    /**
     * 
     * @type {CustomersGet200ResponseParams}
     * @memberof FeaturesGet200Response
     */
    params?: CustomersGet200ResponseParams;
}

/**
 * Check if a given object implements the FeaturesGet200Response interface.
 */
export function instanceOfFeaturesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeaturesGet200ResponseFromJSON(json: any): FeaturesGet200Response {
    return FeaturesGet200ResponseFromJSONTyped(json, false);
}

export function FeaturesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : FeaturesGet200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : CustomersGet200ResponseParamsFromJSON(json['params']),
    };
}

export function FeaturesGet200ResponseToJSON(value?: FeaturesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': FeaturesGet200ResponseDataToJSON(value.data),
        'params': CustomersGet200ResponseParamsToJSON(value.params),
    };
}

