/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface FeaturesIdCheckGet200ResponseParams
 */
export interface FeaturesIdCheckGet200ResponseParams {
    /**
     * 
     * @type {string}
     * @memberof FeaturesIdCheckGet200ResponseParams
     */
    companyId?: string;
}

/**
 * Check if a given object implements the FeaturesIdCheckGet200ResponseParams interface.
 */
export function instanceOfFeaturesIdCheckGet200ResponseParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeaturesIdCheckGet200ResponseParamsFromJSON(json: any): FeaturesIdCheckGet200ResponseParams {
    return FeaturesIdCheckGet200ResponseParamsFromJSONTyped(json, false);
}

export function FeaturesIdCheckGet200ResponseParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturesIdCheckGet200ResponseParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
    };
}

export function FeaturesIdCheckGet200ResponseParamsToJSON(value?: FeaturesIdCheckGet200ResponseParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
    };
}

