/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetApiKey200ResponseData } from './GetApiKey200ResponseData';
import {
    GetApiKey200ResponseDataFromJSON,
    GetApiKey200ResponseDataFromJSONTyped,
    GetApiKey200ResponseDataToJSON,
} from './GetApiKey200ResponseData';

/**
 * 
 * @export
 * @interface GetApiKey200Response
 */
export interface GetApiKey200Response {
    /**
     * 
     * @type {GetApiKey200ResponseData}
     * @memberof GetApiKey200Response
     */
    data?: GetApiKey200ResponseData;
    /**
     * 
     * @type {any}
     * @memberof GetApiKey200Response
     */
    params?: any | null;
}

/**
 * Check if a given object implements the GetApiKey200Response interface.
 */
export function instanceOfGetApiKey200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetApiKey200ResponseFromJSON(json: any): GetApiKey200Response {
    return GetApiKey200ResponseFromJSONTyped(json, false);
}

export function GetApiKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiKey200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : GetApiKey200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function GetApiKey200ResponseToJSON(value?: GetApiKey200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetApiKey200ResponseDataToJSON(value.data),
        'params': value.params,
    };
}

