/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The returned resource
 * @export
 * @interface GetApiKey200ResponseData
 */
export interface GetApiKey200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    environmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    lastUsedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetApiKey200ResponseData
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetApiKey200ResponseData
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the GetApiKey200ResponseData interface.
 */
export function instanceOfGetApiKey200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetApiKey200ResponseDataFromJSON(json: any): GetApiKey200ResponseData {
    return GetApiKey200ResponseDataFromJSONTyped(json, false);
}

export function GetApiKey200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiKey200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : json['last_used_at'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function GetApiKey200ResponseDataToJSON(value?: GetApiKey200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'description': value.description,
        'environment_id': value.environmentId,
        'id': value.id,
        'last_used_at': value.lastUsedAt,
        'name': value.name,
        'scopes': value.scopes,
        'updated_at': value.updatedAt,
    };
}

