/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFeature200ResponseData } from './GetFeature200ResponseData';
import {
    GetFeature200ResponseDataFromJSON,
    GetFeature200ResponseDataFromJSONTyped,
    GetFeature200ResponseDataToJSON,
} from './GetFeature200ResponseData';

/**
 * 
 * @export
 * @interface GetFeature200Response
 */
export interface GetFeature200Response {
    /**
     * 
     * @type {GetFeature200ResponseData}
     * @memberof GetFeature200Response
     */
    data?: GetFeature200ResponseData;
    /**
     * 
     * @type {any}
     * @memberof GetFeature200Response
     */
    params?: any | null;
}

/**
 * Check if a given object implements the GetFeature200Response interface.
 */
export function instanceOfGetFeature200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFeature200ResponseFromJSON(json: any): GetFeature200Response {
    return GetFeature200ResponseFromJSONTyped(json, false);
}

export function GetFeature200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeature200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : GetFeature200ResponseDataFromJSON(json['data']),
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function GetFeature200ResponseToJSON(value?: GetFeature200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetFeature200ResponseDataToJSON(value.data),
        'params': value.params,
    };
}

