/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeatures200ResponseDataInnerFlagsInner } from './CreateFeatures200ResponseDataInnerFlagsInner';
import {
    CreateFeatures200ResponseDataInnerFlagsInnerFromJSON,
    CreateFeatures200ResponseDataInnerFlagsInnerFromJSONTyped,
    CreateFeatures200ResponseDataInnerFlagsInnerToJSON,
} from './CreateFeatures200ResponseDataInnerFlagsInner';
import type { ListFeatures200ResponseDataInner } from './ListFeatures200ResponseDataInner';
import {
    ListFeatures200ResponseDataInnerFromJSON,
    ListFeatures200ResponseDataInnerFromJSONTyped,
    ListFeatures200ResponseDataInnerToJSON,
} from './ListFeatures200ResponseDataInner';

/**
 * The returned resource
 * @export
 * @interface GetFeature200ResponseData
 */
export interface GetFeature200ResponseData {
    /**
     * 
     * @type {ListFeatures200ResponseDataInner}
     * @memberof GetFeature200ResponseData
     */
    feature?: ListFeatures200ResponseDataInner;
    /**
     * 
     * @type {Array<CreateFeatures200ResponseDataInnerFlagsInner>}
     * @memberof GetFeature200ResponseData
     */
    flags?: Array<CreateFeatures200ResponseDataInnerFlagsInner>;
}

/**
 * Check if a given object implements the GetFeature200ResponseData interface.
 */
export function instanceOfGetFeature200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFeature200ResponseDataFromJSON(json: any): GetFeature200ResponseData {
    return GetFeature200ResponseDataFromJSONTyped(json, false);
}

export function GetFeature200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeature200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feature': !exists(json, 'feature') ? undefined : ListFeatures200ResponseDataInnerFromJSON(json['feature']),
        'flags': !exists(json, 'flags') ? undefined : ((json['flags'] as Array<any>).map(CreateFeatures200ResponseDataInnerFlagsInnerFromJSON)),
    };
}

export function GetFeature200ResponseDataToJSON(value?: GetFeature200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feature': ListFeatures200ResponseDataInnerToJSON(value.feature),
        'flags': value.flags === undefined ? undefined : ((value.flags as Array<any>).map(CreateFeatures200ResponseDataInnerFlagsInnerToJSON)),
    };
}

