/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListFlagValues200ResponseParams
 */
export interface ListFlagValues200ResponseParams {
    /**
     * 
     * @type {string}
     * @memberof ListFlagValues200ResponseParams
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFlagValues200ResponseParams
     */
    dir?: string;
    /**
     * 
     * @type {number}
     * @memberof ListFlagValues200ResponseParams
     */
    entityType?: number;
    /**
     * 
     * @type {string}
     * @memberof ListFlagValues200ResponseParams
     */
    flagId?: string;
    /**
     * 
     * @type {number}
     * @memberof ListFlagValues200ResponseParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListFlagValues200ResponseParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListFlagValues200ResponseParams
     */
    order?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFlagValues200ResponseParams
     */
    userId?: string;
}

/**
 * Check if a given object implements the ListFlagValues200ResponseParams interface.
 */
export function instanceOfListFlagValues200ResponseParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListFlagValues200ResponseParamsFromJSON(json: any): ListFlagValues200ResponseParams {
    return ListFlagValues200ResponseParamsFromJSONTyped(json, false);
}

export function ListFlagValues200ResponseParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFlagValues200ResponseParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'entityType': !exists(json, 'entity_type') ? undefined : json['entity_type'],
        'flagId': !exists(json, 'flag_id') ? undefined : json['flag_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function ListFlagValues200ResponseParamsToJSON(value?: ListFlagValues200ResponseParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'dir': value.dir,
        'entity_type': value.entityType,
        'flag_id': value.flagId,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
        'user_id': value.userId,
    };
}

