/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListFlags200ResponseParams
 */
export interface ListFlags200ResponseParams {
    /**
     * 
     * @type {string}
     * @memberof ListFlags200ResponseParams
     */
    dir?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFlags200ResponseParams
     */
    featureId?: string;
    /**
     * 
     * @type {number}
     * @memberof ListFlags200ResponseParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListFlags200ResponseParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListFlags200ResponseParams
     */
    order?: string;
}

/**
 * Check if a given object implements the ListFlags200ResponseParams interface.
 */
export function instanceOfListFlags200ResponseParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListFlags200ResponseParamsFromJSON(json: any): ListFlags200ResponseParams {
    return ListFlags200ResponseParamsFromJSONTyped(json, false);
}

export function ListFlags200ResponseParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFlags200ResponseParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function ListFlags200ResponseParamsToJSON(value?: ListFlags200ResponseParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dir': value.dir,
        'feature_id': value.featureId,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
    };
}

