/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListFlagsParams
 */
export interface ListFlagsParams {
    /**
     * 
     * @type {string}
     * @memberof ListFlagsParams
     */
    dir?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFlagsParams
     */
    featureId?: string;
    /**
     * 
     * @type {number}
     * @memberof ListFlagsParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListFlagsParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListFlagsParams
     */
    order?: string;
}

/**
 * Check if a given object implements the ListFlagsParams interface.
 */
export function instanceOfListFlagsParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListFlagsParamsFromJSON(json: any): ListFlagsParams {
    return ListFlagsParamsFromJSONTyped(json, false);
}

export function ListFlagsParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFlagsParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function ListFlagsParamsToJSON(value?: ListFlagsParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dir': value.dir,
        'feature_id': value.featureId,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
    };
}

