/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListEventsParams
 */
export interface ListEventsParams {
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    dir?: string;
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    eventSubtype?: string;
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    featureId?: string;
    /**
     * 
     * @type {number}
     * @memberof ListEventsParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListEventsParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    order?: string;
    /**
     * 
     * @type {string}
     * @memberof ListEventsParams
     */
    userId?: string;
}

/**
 * Check if a given object implements the ListEventsParams interface.
 */
export function instanceOfListEventsParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListEventsParamsFromJSON(json: any): ListEventsParams {
    return ListEventsParamsFromJSONTyped(json, false);
}

export function ListEventsParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEventsParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'eventSubtype': !exists(json, 'event_subtype') ? undefined : json['event_subtype'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function ListEventsParamsToJSON(value?: ListEventsParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'dir': value.dir,
        'event_subtype': value.eventSubtype,
        'feature_id': value.featureId,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
        'user_id': value.userId,
    };
}

