/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListApiKeys200ResponseDataInner } from './ListApiKeys200ResponseDataInner';
import {
    ListApiKeys200ResponseDataInnerFromJSON,
    ListApiKeys200ResponseDataInnerFromJSONTyped,
    ListApiKeys200ResponseDataInnerToJSON,
} from './ListApiKeys200ResponseDataInner';
import type { ListApiKeys200ResponseParams } from './ListApiKeys200ResponseParams';
import {
    ListApiKeys200ResponseParamsFromJSON,
    ListApiKeys200ResponseParamsFromJSONTyped,
    ListApiKeys200ResponseParamsToJSON,
} from './ListApiKeys200ResponseParams';

/**
 * 
 * @export
 * @interface ListApiKeys200Response
 */
export interface ListApiKeys200Response {
    /**
     * The returned resource
     * @type {Array<ListApiKeys200ResponseDataInner>}
     * @memberof ListApiKeys200Response
     */
    data?: Array<ListApiKeys200ResponseDataInner>;
    /**
     * 
     * @type {ListApiKeys200ResponseParams}
     * @memberof ListApiKeys200Response
     */
    params?: ListApiKeys200ResponseParams;
}

/**
 * Check if a given object implements the ListApiKeys200Response interface.
 */
export function instanceOfListApiKeys200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListApiKeys200ResponseFromJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseFromJSONTyped(json, false);
}

export function ListApiKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeys200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ListApiKeys200ResponseDataInnerFromJSON)),
        'params': !exists(json, 'params') ? undefined : ListApiKeys200ResponseParamsFromJSON(json['params']),
    };
}

export function ListApiKeys200ResponseToJSON(value?: ListApiKeys200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ListApiKeys200ResponseDataInnerToJSON)),
        'params': ListApiKeys200ResponseParamsToJSON(value.params),
    };
}

