/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCompanies200ResponseDataInner
 */
export interface ListCompanies200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200ResponseDataInner
     */
    accountId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListCompanies200ResponseDataInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200ResponseDataInner
     */
    environmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListCompanies200ResponseDataInner
     */
    lastSeenAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListCompanies200ResponseDataInner
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ListCompanies200ResponseDataInner interface.
 */
export function instanceOfListCompanies200ResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListCompanies200ResponseDataInnerFromJSON(json: any): ListCompanies200ResponseDataInner {
    return ListCompanies200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListCompanies200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCompanies200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastSeenAt': !exists(json, 'last_seen_at') ? undefined : (new Date(json['last_seen_at'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ListCompanies200ResponseDataInnerToJSON(value?: ListCompanies200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'environment_id': value.environmentId,
        'id': value.id,
        'last_seen_at': value.lastSeenAt === undefined ? undefined : (value.lastSeenAt.toISOString()),
        'name': value.name,
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

