/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomersGet200ResponseParams } from './CustomersGet200ResponseParams';
import {
    CustomersGet200ResponseParamsFromJSON,
    CustomersGet200ResponseParamsFromJSONTyped,
    CustomersGet200ResponseParamsToJSON,
} from './CustomersGet200ResponseParams';
import type { MetricsGet200ResponseDataInner } from './MetricsGet200ResponseDataInner';
import {
    MetricsGet200ResponseDataInnerFromJSON,
    MetricsGet200ResponseDataInnerFromJSONTyped,
    MetricsGet200ResponseDataInnerToJSON,
} from './MetricsGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface MetricsGet200Response
 */
export interface MetricsGet200Response {
    /**
     * The returned resource
     * @type {Array<MetricsGet200ResponseDataInner>}
     * @memberof MetricsGet200Response
     */
    data?: Array<MetricsGet200ResponseDataInner>;
    /**
     * 
     * @type {CustomersGet200ResponseParams}
     * @memberof MetricsGet200Response
     */
    params?: CustomersGet200ResponseParams;
}

/**
 * Check if a given object implements the MetricsGet200Response interface.
 */
export function instanceOfMetricsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetricsGet200ResponseFromJSON(json: any): MetricsGet200Response {
    return MetricsGet200ResponseFromJSONTyped(json, false);
}

export function MetricsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(MetricsGet200ResponseDataInnerFromJSON)),
        'params': !exists(json, 'params') ? undefined : CustomersGet200ResponseParamsFromJSON(json['params']),
    };
}

export function MetricsGet200ResponseToJSON(value?: MetricsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(MetricsGet200ResponseDataInnerToJSON)),
        'params': CustomersGet200ResponseParamsToJSON(value.params),
    };
}

