/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The returned resource
 * @export
 * @interface MetricCountsGet200ResponseData
 */
export interface MetricCountsGet200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof MetricCountsGet200ResponseData
     */
    accountId?: string;
    /**
     * 
     * @type {Date}
     * @memberof MetricCountsGet200ResponseData
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MetricCountsGet200ResponseData
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricCountsGet200ResponseData
     */
    definitionId?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricCountsGet200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof MetricCountsGet200ResponseData
     */
    startTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof MetricCountsGet200ResponseData
     */
    value?: number;
}

/**
 * Check if a given object implements the MetricCountsGet200ResponseData interface.
 */
export function instanceOfMetricCountsGet200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetricCountsGet200ResponseDataFromJSON(json: any): MetricCountsGet200ResponseData {
    return MetricCountsGet200ResponseDataFromJSONTyped(json, false);
}

export function MetricCountsGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricCountsGet200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'definitionId': !exists(json, 'definition_id') ? undefined : json['definition_id'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function MetricCountsGet200ResponseDataToJSON(value?: MetricCountsGet200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'customer_id': value.customerId,
        'definition_id': value.definitionId,
        'id': value.id,
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'value': value.value,
    };
}

