/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlansGet200ResponseDataInner
 */
export interface PlansGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof PlansGet200ResponseDataInner
     */
    accountId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlansGet200ResponseDataInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PlansGet200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlansGet200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlansGet200ResponseDataInner
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the PlansGet200ResponseDataInner interface.
 */
export function instanceOfPlansGet200ResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlansGet200ResponseDataInnerFromJSON(json: any): PlansGet200ResponseDataInner {
    return PlansGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function PlansGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlansGet200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function PlansGet200ResponseDataInnerToJSON(value?: PlansGet200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'id': value.id,
        'name': value.name,
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

