/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFeature201ResponseDataFlagsInnerRulesInner } from './CreateFeature201ResponseDataFlagsInnerRulesInner';
import {
    CreateFeature201ResponseDataFlagsInnerRulesInnerFromJSON,
    CreateFeature201ResponseDataFlagsInnerRulesInnerFromJSONTyped,
    CreateFeature201ResponseDataFlagsInnerRulesInnerToJSON,
} from './CreateFeature201ResponseDataFlagsInnerRulesInner';

/**
 * The updated resource
 * @export
 * @interface UpdateFlag200ResponseData
 */
export interface UpdateFlag200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    createdAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFlag200ResponseData
     */
    defaultValue: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    featureId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    flagType: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    name: string;
    /**
     * 
     * @type {Array<CreateFeature201ResponseDataFlagsInnerRulesInner>}
     * @memberof UpdateFlag200ResponseData
     */
    rules: Array<CreateFeature201ResponseDataFlagsInnerRulesInner>;
    /**
     * 
     * @type {string}
     * @memberof UpdateFlag200ResponseData
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the UpdateFlag200ResponseData interface.
 */
export function instanceOfUpdateFlag200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "defaultValue" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "flagType" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "rules" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function UpdateFlag200ResponseDataFromJSON(json: any): UpdateFlag200ResponseData {
    return UpdateFlag200ResponseDataFromJSONTyped(json, false);
}

export function UpdateFlag200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFlag200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'defaultValue': json['default_value'],
        'description': json['description'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'flagType': json['flag_type'],
        'id': json['id'],
        'key': json['key'],
        'name': json['name'],
        'rules': ((json['rules'] as Array<any>).map(CreateFeature201ResponseDataFlagsInnerRulesInnerFromJSON)),
        'updatedAt': json['updated_at'],
    };
}

export function UpdateFlag200ResponseDataToJSON(value?: UpdateFlag200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'default_value': value.defaultValue,
        'description': value.description,
        'feature_id': value.featureId,
        'flag_type': value.flagType,
        'id': value.id,
        'key': value.key,
        'name': value.name,
        'rules': ((value.rules as Array<any>).map(CreateFeature201ResponseDataFlagsInnerRulesInnerToJSON)),
        'updated_at': value.updatedAt,
    };
}

