/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The updated resource
 * @export
 * @interface UpdateApiKey200ResponseData
 */
export interface UpdateApiKey200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    environmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    lastUsedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateApiKey200ResponseData
     */
    scopes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateApiKey200ResponseData
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the UpdateApiKey200ResponseData interface.
 */
export function instanceOfUpdateApiKey200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "scopes" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function UpdateApiKey200ResponseDataFromJSON(json: any): UpdateApiKey200ResponseData {
    return UpdateApiKey200ResponseDataFromJSONTyped(json, false);
}

export function UpdateApiKey200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApiKey200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'id': json['id'],
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : json['last_used_at'],
        'name': json['name'],
        'scopes': json['scopes'],
        'updatedAt': json['updated_at'],
    };
}

export function UpdateApiKey200ResponseDataToJSON(value?: UpdateApiKey200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'description': value.description,
        'environment_id': value.environmentId,
        'id': value.id,
        'last_used_at': value.lastUsedAt,
        'name': value.name,
        'scopes': value.scopes,
        'updated_at': value.updatedAt,
    };
}

