/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The returned resource
 * @export
 * @interface UpdateEnvironment200ResponseData
 */
export interface UpdateEnvironment200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironment200ResponseData
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironment200ResponseData
     */
    environmentType?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironment200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironment200ResponseData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironment200ResponseData
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the UpdateEnvironment200ResponseData interface.
 */
export function instanceOfUpdateEnvironment200ResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateEnvironment200ResponseDataFromJSON(json: any): UpdateEnvironment200ResponseData {
    return UpdateEnvironment200ResponseDataFromJSONTyped(json, false);
}

export function UpdateEnvironment200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEnvironment200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'environmentType': !exists(json, 'environment_type') ? undefined : json['environment_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function UpdateEnvironment200ResponseDataToJSON(value?: UpdateEnvironment200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'environment_type': value.environmentType,
        'id': value.id,
        'name': value.name,
        'updated_at': value.updatedAt,
    };
}

