/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The created resource
 * @export
 * @interface ApiKeyCreateResponseData
 */
export interface ApiKeyCreateResponseData {
  /**
   *
   * @type {Date}
   * @memberof ApiKeyCreateResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof ApiKeyCreateResponseData
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof ApiKeyCreateResponseData
   */
  environmentId?: string;
  /**
   *
   * @type {string}
   * @memberof ApiKeyCreateResponseData
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof ApiKeyCreateResponseData
   */
  lastUsedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof ApiKeyCreateResponseData
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ApiKeyCreateResponseData
   */
  scopes: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ApiKeyCreateResponseData
   */
  secret: string;
  /**
   *
   * @type {Date}
   * @memberof ApiKeyCreateResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the ApiKeyCreateResponseData interface.
 */
export function instanceOfApiKeyCreateResponseData(value: object): boolean {
  if (!("createdAt" in value)) return false;
  if (!("id" in value)) return false;
  if (!("name" in value)) return false;
  if (!("scopes" in value)) return false;
  if (!("secret" in value)) return false;
  if (!("updatedAt" in value)) return false;
  return true;
}

export function ApiKeyCreateResponseDataFromJSON(
  json: any,
): ApiKeyCreateResponseData {
  return ApiKeyCreateResponseDataFromJSONTyped(json, false);
}

export function ApiKeyCreateResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApiKeyCreateResponseData {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["created_at"]),
    description: json["description"] == null ? undefined : json["description"],
    environmentId:
      json["environment_id"] == null ? undefined : json["environment_id"],
    id: json["id"],
    lastUsedAt:
      json["last_used_at"] == null ? undefined : new Date(json["last_used_at"]),
    name: json["name"],
    scopes: json["scopes"],
    secret: json["secret"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function ApiKeyCreateResponseDataToJSON(
  value?: ApiKeyCreateResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"].toISOString(),
    description: value["description"],
    environment_id: value["environmentId"],
    id: value["id"],
    last_used_at:
      value["lastUsedAt"] == null
        ? undefined
        : (value["lastUsedAt"] as any).toISOString(),
    name: value["name"],
    scopes: value["scopes"],
    secret: value["secret"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
