/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrUpdateConditionGroupRequestBody } from './CreateOrUpdateConditionGroupRequestBody';
import {
    CreateOrUpdateConditionGroupRequestBodyFromJSON,
    CreateOrUpdateConditionGroupRequestBodyFromJSONTyped,
    CreateOrUpdateConditionGroupRequestBodyToJSON,
} from './CreateOrUpdateConditionGroupRequestBody';
import type { CreateOrUpdateConditionRequestBody } from './CreateOrUpdateConditionRequestBody';
import {
    CreateOrUpdateConditionRequestBodyFromJSON,
    CreateOrUpdateConditionRequestBodyFromJSONTyped,
    CreateOrUpdateConditionRequestBodyToJSON,
} from './CreateOrUpdateConditionRequestBody';

/**
 * 
 * @export
 * @interface AudienceRequestBody
 */
export interface AudienceRequestBody {
    /**
     * 
     * @type {Array<CreateOrUpdateConditionGroupRequestBody>}
     * @memberof AudienceRequestBody
     */
    conditionGroups: Array<CreateOrUpdateConditionGroupRequestBody>;
    /**
     * 
     * @type {Array<CreateOrUpdateConditionRequestBody>}
     * @memberof AudienceRequestBody
     */
    conditions: Array<CreateOrUpdateConditionRequestBody>;
    /**
     * Page limit (default 100)
     * @type {number}
     * @memberof AudienceRequestBody
     */
    limit?: number;
    /**
     * Page offset (default 0)
     * @type {number}
     * @memberof AudienceRequestBody
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof AudienceRequestBody
     */
    q?: string;
}

/**
 * Check if a given object implements the AudienceRequestBody interface.
 */
export function instanceOfAudienceRequestBody(value: object): boolean {
    if (!('conditionGroups' in value)) return false;
    if (!('conditions' in value)) return false;
    return true;
}

export function AudienceRequestBodyFromJSON(json: any): AudienceRequestBody {
    return AudienceRequestBodyFromJSONTyped(json, false);
}

export function AudienceRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudienceRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'conditionGroups': ((json['condition_groups'] as Array<any>).map(CreateOrUpdateConditionGroupRequestBodyFromJSON)),
        'conditions': ((json['conditions'] as Array<any>).map(CreateOrUpdateConditionRequestBodyFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'q': json['q'] == null ? undefined : json['q'],
    };
}

export function AudienceRequestBodyToJSON(value?: AudienceRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'condition_groups': ((value['conditionGroups'] as Array<any>).map(CreateOrUpdateConditionGroupRequestBodyToJSON)),
        'conditions': ((value['conditions'] as Array<any>).map(CreateOrUpdateConditionRequestBodyToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'q': value['q'],
    };
}

