/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The returned resource
 * @export
 * @interface CheckFlagResponseData
 */
export interface CheckFlagResponseData {
    /**
     * 
     * @type {string}
     * @memberof CheckFlagResponseData
     */
    companyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckFlagResponseData
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckFlagResponseData
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof CheckFlagResponseData
     */
    ruleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckFlagResponseData
     */
    userId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CheckFlagResponseData
     */
    value: boolean;
}

/**
 * Check if a given object implements the CheckFlagResponseData interface.
 */
export function instanceOfCheckFlagResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reason" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CheckFlagResponseDataFromJSON(json: any): CheckFlagResponseData {
    return CheckFlagResponseDataFromJSONTyped(json, false);
}

export function CheckFlagResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckFlagResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'reason': json['reason'],
        'ruleId': !exists(json, 'rule_id') ? undefined : json['rule_id'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'value': json['value'],
    };
}

export function CheckFlagResponseDataToJSON(value?: CheckFlagResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'error': value.error,
        'reason': value.reason,
        'rule_id': value.ruleId,
        'user_id': value.userId,
        'value': value.value,
    };
}

