/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckFlagOutputWithFlagKey } from "./CheckFlagOutputWithFlagKey";
import {
  CheckFlagOutputWithFlagKeyFromJSON,
  CheckFlagOutputWithFlagKeyFromJSONTyped,
  CheckFlagOutputWithFlagKeyToJSON,
} from "./CheckFlagOutputWithFlagKey";

/**
 * The created resource
 * @export
 * @interface CheckFlagsResponseData
 */
export interface CheckFlagsResponseData {
  /**
   *
   * @type {Array<CheckFlagOutputWithFlagKey>}
   * @memberof CheckFlagsResponseData
   */
  flags: Array<CheckFlagOutputWithFlagKey>;
}

/**
 * Check if a given object implements the CheckFlagsResponseData interface.
 */
export function instanceOfCheckFlagsResponseData(value: object): boolean {
  if (!("flags" in value)) return false;
  return true;
}

export function CheckFlagsResponseDataFromJSON(
  json: any,
): CheckFlagsResponseData {
  return CheckFlagsResponseDataFromJSONTyped(json, false);
}

export function CheckFlagsResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckFlagsResponseData {
  if (json == null) {
    return json;
  }
  return {
    flags: (json["flags"] as Array<any>).map(
      CheckFlagOutputWithFlagKeyFromJSON,
    ),
  };
}

export function CheckFlagsResponseDataToJSON(
  value?: CheckFlagsResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    flags: (value["flags"] as Array<any>).map(CheckFlagOutputWithFlagKeyToJSON),
  };
}
