/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CountResponse } from './CountResponse';
import {
    CountResponseFromJSON,
    CountResponseFromJSONTyped,
    CountResponseToJSON,
} from './CountResponse';

/**
 * 
 * @export
 * @interface CountUsersAudienceResponse
 */
export interface CountUsersAudienceResponse {
    /**
     * 
     * @type {CountResponse}
     * @memberof CountUsersAudienceResponse
     */
    data: CountResponse;
    /**
     * Input parameters
     * @type {object}
     * @memberof CountUsersAudienceResponse
     */
    params: object;
}

/**
 * Check if a given object implements the CountUsersAudienceResponse interface.
 */
export function instanceOfCountUsersAudienceResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function CountUsersAudienceResponseFromJSON(json: any): CountUsersAudienceResponse {
    return CountUsersAudienceResponseFromJSONTyped(json, false);
}

export function CountUsersAudienceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountUsersAudienceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CountResponseFromJSON(json['data']),
        'params': json['params'],
    };
}

export function CountUsersAudienceResponseToJSON(value?: CountUsersAudienceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CountResponseToJSON(value.data),
        'params': value.params,
    };
}

