/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface CountEventsParams
 */
export interface CountEventsParams {
    /**
     * 
     * @type {string}
     * @memberof CountEventsParams
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CountEventsParams
     */
    eventSubtype?: string;
    /**
     * 
     * @type {string}
     * @memberof CountEventsParams
     */
    featureId?: string;
    /**
     * 
     * @type {string}
     * @memberof CountEventsParams
     */
    userId?: string;
}

/**
 * Check if a given object implements the CountEventsParams interface.
 */
export function instanceOfCountEventsParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CountEventsParamsFromJSON(json: any): CountEventsParams {
    return CountEventsParamsFromJSONTyped(json, false);
}

export function CountEventsParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountEventsParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'eventSubtype': !exists(json, 'event_subtype') ? undefined : json['event_subtype'],
        'featureId': !exists(json, 'feature_id') ? undefined : json['feature_id'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function CountEventsParamsToJSON(value?: CountEventsParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'event_subtype': value.eventSubtype,
        'feature_id': value.featureId,
        'user_id': value.userId,
    };
}

