/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface CountUsersParams
 */
export interface CountUsersParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof CountUsersParams
     */
    ids?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CountUsersParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof CountUsersParams
     */
    offset?: number;
}

/**
 * Check if a given object implements the CountUsersParams interface.
 */
export function instanceOfCountUsersParams(value: object): boolean {
    return true;
}

export function CountUsersParamsFromJSON(json: any): CountUsersParams {
    return CountUsersParamsFromJSONTyped(json, false);
}

export function CountUsersParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountUsersParams {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function CountUsersParamsToJSON(value?: CountUsersParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ids': value['ids'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

