/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateBillingSubscriptionsRequestBody
 */
export interface CreateBillingSubscriptionsRequestBody {
  /**
   *
   * @type {string}
   * @memberof CreateBillingSubscriptionsRequestBody
   */
  customerExternalId: string;
  /**
   *
   * @type {Date}
   * @memberof CreateBillingSubscriptionsRequestBody
   */
  expiredAt: Date;
  /**
   *
   * @type {string}
   * @memberof CreateBillingSubscriptionsRequestBody
   */
  interval?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateBillingSubscriptionsRequestBody
   */
  productExternalIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateBillingSubscriptionsRequestBody
   */
  subscriptionExternalId: string;
}

/**
 * Check if a given object implements the CreateBillingSubscriptionsRequestBody interface.
 */
export function instanceOfCreateBillingSubscriptionsRequestBody(
  value: object,
): boolean {
  if (!("customerExternalId" in value)) return false;
  if (!("expiredAt" in value)) return false;
  if (!("productExternalIds" in value)) return false;
  if (!("subscriptionExternalId" in value)) return false;
  return true;
}

export function CreateBillingSubscriptionsRequestBodyFromJSON(
  json: any,
): CreateBillingSubscriptionsRequestBody {
  return CreateBillingSubscriptionsRequestBodyFromJSONTyped(json, false);
}

export function CreateBillingSubscriptionsRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateBillingSubscriptionsRequestBody {
  if (json == null) {
    return json;
  }
  return {
    customerExternalId: json["customer_external_id"],
    expiredAt: new Date(json["expired_at"]),
    interval: json["interval"] == null ? undefined : json["interval"],
    productExternalIds: json["product_external_ids"],
    subscriptionExternalId: json["subscription_external_id"],
  };
}

export function CreateBillingSubscriptionsRequestBodyToJSON(
  value?: CreateBillingSubscriptionsRequestBody | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    customer_external_id: value["customerExternalId"],
    expired_at: value["expiredAt"].toISOString(),
    interval: value["interval"],
    product_external_ids: value["productExternalIds"],
    subscription_external_id: value["subscriptionExternalId"],
  };
}
