/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateWebhookRequestBody
 */
export interface CreateWebhookRequestBody {
  /**
   *
   * @type {string}
   * @memberof CreateWebhookRequestBody
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateWebhookRequestBody
   */
  requestTypes: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateWebhookRequestBody
   */
  url: string;
}

/**
 * Check if a given object implements the CreateWebhookRequestBody interface.
 */
export function instanceOfCreateWebhookRequestBody(value: object): boolean {
  if (!("name" in value)) return false;
  if (!("requestTypes" in value)) return false;
  if (!("url" in value)) return false;
  return true;
}

export function CreateWebhookRequestBodyFromJSON(
  json: any,
): CreateWebhookRequestBody {
  return CreateWebhookRequestBodyFromJSONTyped(json, false);
}

export function CreateWebhookRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWebhookRequestBody {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    requestTypes: json["request_types"],
    url: json["url"],
  };
}

export function CreateWebhookRequestBodyToJSON(
  value?: CreateWebhookRequestBody | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    name: value["name"],
    request_types: value["requestTypes"],
    url: value["url"],
  };
}
