/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The created resource
 * @export
 * @interface CRMProductResponseData
 */
export interface CRMProductResponseData {
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  accountId: string;
  /**
   *
   * @type {Date}
   * @memberof CRMProductResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  currency: string;
  /**
   *
   * @type {Date}
   * @memberof CRMProductResponseData
   */
  deletedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  environmentId: string;
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  externalId: string;
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof CRMProductResponseData
   */
  price: number;
  /**
   *
   * @type {string}
   * @memberof CRMProductResponseData
   */
  productId: string;
  /**
   *
   * @type {number}
   * @memberof CRMProductResponseData
   */
  quantity: number;
  /**
   *
   * @type {Date}
   * @memberof CRMProductResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the CRMProductResponseData interface.
 */
export function instanceOfCRMProductResponseData(value: object): boolean {
  if (!("accountId" in value)) return false;
  if (!("createdAt" in value)) return false;
  if (!("currency" in value)) return false;
  if (!("environmentId" in value)) return false;
  if (!("externalId" in value)) return false;
  if (!("name" in value)) return false;
  if (!("price" in value)) return false;
  if (!("productId" in value)) return false;
  if (!("quantity" in value)) return false;
  if (!("updatedAt" in value)) return false;
  return true;
}

export function CRMProductResponseDataFromJSON(
  json: any,
): CRMProductResponseData {
  return CRMProductResponseDataFromJSONTyped(json, false);
}

export function CRMProductResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CRMProductResponseData {
  if (json == null) {
    return json;
  }
  return {
    accountId: json["account_id"],
    createdAt: new Date(json["created_at"]),
    currency: json["currency"],
    deletedAt:
      json["deleted_at"] == null ? undefined : new Date(json["deleted_at"]),
    environmentId: json["environment_id"],
    externalId: json["external_id"],
    name: json["name"],
    price: json["price"],
    productId: json["product_id"],
    quantity: json["quantity"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function CRMProductResponseDataToJSON(
  value?: CRMProductResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    account_id: value["accountId"],
    created_at: value["createdAt"].toISOString(),
    currency: value["currency"],
    deleted_at:
      value["deletedAt"] == null
        ? undefined
        : (value["deletedAt"] as any).toISOString(),
    environment_id: value["environmentId"],
    external_id: value["externalId"],
    name: value["name"],
    price: value["price"],
    product_id: value["productId"],
    quantity: value["quantity"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
