/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeleteResponse } from './DeleteResponse';
import {
    DeleteResponseFromJSON,
    DeleteResponseFromJSONTyped,
    DeleteResponseToJSON,
} from './DeleteResponse';

/**
 * 
 * @export
 * @interface DeleteCompanyMembershipResponse
 */
export interface DeleteCompanyMembershipResponse {
    /**
     * 
     * @type {DeleteResponse}
     * @memberof DeleteCompanyMembershipResponse
     */
    data: DeleteResponse;
    /**
     * Input parameters
     * @type {object}
     * @memberof DeleteCompanyMembershipResponse
     */
    params: object;
}

/**
 * Check if a given object implements the DeleteCompanyMembershipResponse interface.
 */
export function instanceOfDeleteCompanyMembershipResponse(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('params' in value)) return false;
    return true;
}

export function DeleteCompanyMembershipResponseFromJSON(json: any): DeleteCompanyMembershipResponse {
    return DeleteCompanyMembershipResponseFromJSONTyped(json, false);
}

export function DeleteCompanyMembershipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCompanyMembershipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': DeleteResponseFromJSON(json['data']),
        'params': json['params'],
    };
}

export function DeleteCompanyMembershipResponseToJSON(value?: DeleteCompanyMembershipResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': DeleteResponseToJSON(value['data']),
        'params': value['params'],
    };
}

