/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Information about the company associated with the user; required only if it is a new user
 * @export
 * @interface EventBodyIdentifyCompany
 */
export interface EventBodyIdentifyCompany {
  /**
   * Key-value pairs to identify the company
   * @type {object}
   * @memberof EventBodyIdentifyCompany
   */
  keys: object;
  /**
   * The display name of the company; required only if it is a new company
   * @type {string}
   * @memberof EventBodyIdentifyCompany
   */
  name?: string;
  /**
   * A map of company trait names to trait values
   * @type {object}
   * @memberof EventBodyIdentifyCompany
   */
  traits?: object;
}

/**
 * Check if a given object implements the EventBodyIdentifyCompany interface.
 */
export function instanceOfEventBodyIdentifyCompany(value: object): boolean {
  if (!("keys" in value)) return false;
  return true;
}

export function EventBodyIdentifyCompanyFromJSON(
  json: any,
): EventBodyIdentifyCompany {
  return EventBodyIdentifyCompanyFromJSONTyped(json, false);
}

export function EventBodyIdentifyCompanyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EventBodyIdentifyCompany {
  if (json == null) {
    return json;
  }
  return {
    keys: json["keys"],
    name: json["name"] == null ? undefined : json["name"],
    traits: json["traits"] == null ? undefined : json["traits"],
  };
}

export function EventBodyIdentifyCompanyToJSON(
  value?: EventBodyIdentifyCompany | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    keys: value["keys"],
    name: value["name"],
    traits: value["traits"],
  };
}
