/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureResponseData
 */
export interface FeatureResponseData {
    /**
     * 
     * @type {Date}
     * @memberof FeatureResponseData
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    eventSubtype?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    featureType: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    lifecyclePhase?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureResponseData
     */
    traitId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeatureResponseData
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the FeatureResponseData interface.
 */
export function instanceOfFeatureResponseData(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('description' in value)) return false;
    if (!('featureType' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function FeatureResponseDataFromJSON(json: any): FeatureResponseData {
    return FeatureResponseDataFromJSONTyped(json, false);
}

export function FeatureResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'eventSubtype': json['event_subtype'] == null ? undefined : json['event_subtype'],
        'featureType': json['feature_type'],
        'id': json['id'],
        'lifecyclePhase': json['lifecycle_phase'] == null ? undefined : json['lifecycle_phase'],
        'name': json['name'],
        'traitId': json['trait_id'] == null ? undefined : json['trait_id'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function FeatureResponseDataToJSON(value?: FeatureResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'description': value['description'],
        'event_subtype': value['eventSubtype'],
        'feature_type': value['featureType'],
        'id': value['id'],
        'lifecycle_phase': value['lifecyclePhase'],
        'name': value['name'],
        'trait_id': value['traitId'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

