/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityTraitDefinitionResponseData } from './EntityTraitDefinitionResponseData';
import {
    EntityTraitDefinitionResponseDataFromJSON,
    EntityTraitDefinitionResponseDataFromJSONTyped,
    EntityTraitDefinitionResponseDataToJSON,
} from './EntityTraitDefinitionResponseData';

/**
 * 
 * @export
 * @interface GetEntityTraitDefinitionResponse
 */
export interface GetEntityTraitDefinitionResponse {
    /**
     * 
     * @type {EntityTraitDefinitionResponseData}
     * @memberof GetEntityTraitDefinitionResponse
     */
    data: EntityTraitDefinitionResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof GetEntityTraitDefinitionResponse
     */
    params: object;
}

/**
 * Check if a given object implements the GetEntityTraitDefinitionResponse interface.
 */
export function instanceOfGetEntityTraitDefinitionResponse(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('params' in value)) return false;
    return true;
}

export function GetEntityTraitDefinitionResponseFromJSON(json: any): GetEntityTraitDefinitionResponse {
    return GetEntityTraitDefinitionResponseFromJSONTyped(json, false);
}

export function GetEntityTraitDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEntityTraitDefinitionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EntityTraitDefinitionResponseDataFromJSON(json['data']),
        'params': json['params'],
    };
}

export function GetEntityTraitDefinitionResponseToJSON(value?: GetEntityTraitDefinitionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': EntityTraitDefinitionResponseDataToJSON(value['data']),
        'params': value['params'],
    };
}

