/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RuleDetailResponseData } from './RuleDetailResponseData';
import {
    RuleDetailResponseDataFromJSON,
    RuleDetailResponseDataFromJSONTyped,
    RuleDetailResponseDataToJSON,
} from './RuleDetailResponseData';

/**
 * 
 * @export
 * @interface GetRuleResponse
 */
export interface GetRuleResponse {
    /**
     * 
     * @type {RuleDetailResponseData}
     * @memberof GetRuleResponse
     */
    data: RuleDetailResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof GetRuleResponse
     */
    params: object;
}

/**
 * Check if a given object implements the GetRuleResponse interface.
 */
export function instanceOfGetRuleResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function GetRuleResponseFromJSON(json: any): GetRuleResponse {
    return GetRuleResponseFromJSONTyped(json, false);
}

export function GetRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRuleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': RuleDetailResponseDataFromJSON(json['data']),
        'params': json['params'],
    };
}

export function GetRuleResponseToJSON(value?: GetRuleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': RuleDetailResponseDataToJSON(value.data),
        'params': value.params,
    };
}

