/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDetailResponseData } from './UserDetailResponseData';
import {
    UserDetailResponseDataFromJSON,
    UserDetailResponseDataFromJSONTyped,
    UserDetailResponseDataToJSON,
} from './UserDetailResponseData';

/**
 * 
 * @export
 * @interface GetUsersAudienceResponse
 */
export interface GetUsersAudienceResponse {
    /**
     * The returned resources
     * @type {Array<UserDetailResponseData>}
     * @memberof GetUsersAudienceResponse
     */
    data: Array<UserDetailResponseData>;
    /**
     * Input parameters
     * @type {object}
     * @memberof GetUsersAudienceResponse
     */
    params: object;
}

/**
 * Check if a given object implements the GetUsersAudienceResponse interface.
 */
export function instanceOfGetUsersAudienceResponse(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('params' in value)) return false;
    return true;
}

export function GetUsersAudienceResponseFromJSON(json: any): GetUsersAudienceResponse {
    return GetUsersAudienceResponseFromJSONTyped(json, false);
}

export function GetUsersAudienceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersAudienceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserDetailResponseDataFromJSON)),
        'params': json['params'],
    };
}

export function GetUsersAudienceResponseToJSON(value?: GetUsersAudienceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(UserDetailResponseDataToJSON)),
        'params': value['params'],
    };
}

