/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeysRequestBody
 */
export interface KeysRequestBody {
    /**
     * 
     * @type {object}
     * @memberof KeysRequestBody
     */
    keys: object;
}

/**
 * Check if a given object implements the KeysRequestBody interface.
 */
export function instanceOfKeysRequestBody(value: object): boolean {
    if (!('keys' in value)) return false;
    return true;
}

export function KeysRequestBodyFromJSON(json: any): KeysRequestBody {
    return KeysRequestBodyFromJSONTyped(json, false);
}

export function KeysRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeysRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': json['keys'],
    };
}

export function KeysRequestBodyToJSON(value?: KeysRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'keys': value['keys'],
    };
}

