/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface LatestFlagChecksParams
 */
export interface LatestFlagChecksParams {
    /**
     * 
     * @type {string}
     * @memberof LatestFlagChecksParams
     */
    flagId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LatestFlagChecksParams
     */
    flagIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LatestFlagChecksParams
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof LatestFlagChecksParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof LatestFlagChecksParams
     */
    offset?: number;
}

/**
 * Check if a given object implements the LatestFlagChecksParams interface.
 */
export function instanceOfLatestFlagChecksParams(value: object): boolean {
    return true;
}

export function LatestFlagChecksParamsFromJSON(json: any): LatestFlagChecksParams {
    return LatestFlagChecksParamsFromJSONTyped(json, false);
}

export function LatestFlagChecksParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LatestFlagChecksParams {
    if (json == null) {
        return json;
    }
    return {
        
        'flagId': json['flag_id'] == null ? undefined : json['flag_id'],
        'flagIds': json['flag_ids'] == null ? undefined : json['flag_ids'],
        'id': json['id'] == null ? undefined : json['id'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function LatestFlagChecksParamsToJSON(value?: LatestFlagChecksParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'flag_id': value['flagId'],
        'flag_ids': value['flagIds'],
        'id': value['id'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

