/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface ListCompanyPlansParams
 */
export interface ListCompanyPlansParams {
  /**
   *
   * @type {string}
   * @memberof ListCompanyPlansParams
   */
  companyId?: string;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof ListCompanyPlansParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof ListCompanyPlansParams
   */
  offset?: number;
  /**
   *
   * @type {string}
   * @memberof ListCompanyPlansParams
   */
  planId?: string;
}

/**
 * Check if a given object implements the ListCompanyPlansParams interface.
 */
export function instanceOfListCompanyPlansParams(
  value: object,
): value is ListCompanyPlansParams {
  return true;
}

export function ListCompanyPlansParamsFromJSON(
  json: any,
): ListCompanyPlansParams {
  return ListCompanyPlansParamsFromJSONTyped(json, false);
}

export function ListCompanyPlansParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCompanyPlansParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    planId: json["plan_id"] == null ? undefined : json["plan_id"],
  };
}

export function ListCompanyPlansParamsToJSON(
  value?: ListCompanyPlansParams | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    company_id: value["companyId"],
    limit: value["limit"],
    offset: value["offset"],
    plan_id: value["planId"],
  };
}
