/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface ListCompanyMembershipsParams
 */
export interface ListCompanyMembershipsParams {
  /**
   *
   * @type {string}
   * @memberof ListCompanyMembershipsParams
   */
  companyId?: string;
  /**
   *
   * @type {number}
   * @memberof ListCompanyMembershipsParams
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof ListCompanyMembershipsParams
   */
  offset?: number;
  /**
   *
   * @type {string}
   * @memberof ListCompanyMembershipsParams
   */
  userId?: string;
}

/**
 * Check if a given object implements the ListCompanyMembershipsParams interface.
 */
export function instanceOfListCompanyMembershipsParams(value: object): boolean {
  return true;
}

export function ListCompanyMembershipsParamsFromJSON(
  json: any,
): ListCompanyMembershipsParams {
  return ListCompanyMembershipsParamsFromJSONTyped(json, false);
}

export function ListCompanyMembershipsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCompanyMembershipsParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
  };
}

export function ListCompanyMembershipsParamsToJSON(
  value?: ListCompanyMembershipsParams | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    company_id: value["companyId"],
    limit: value["limit"],
    offset: value["offset"],
    user_id: value["userId"],
  };
}
