/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListMetricCountsHourlyParams
 */
export interface ListMetricCountsHourlyParams {
    /**
     * 
     * @type {string}
     * @memberof ListMetricCountsHourlyParams
     */
    companyId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListMetricCountsHourlyParams
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListMetricCountsHourlyParams
     */
    eventSubtype?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMetricCountsHourlyParams
     */
    eventSubtypes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ListMetricCountsHourlyParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListMetricCountsHourlyParams
     */
    offset?: number;
    /**
     * 
     * @type {Date}
     * @memberof ListMetricCountsHourlyParams
     */
    startTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListMetricCountsHourlyParams
     */
    userId?: string;
}

/**
 * Check if a given object implements the ListMetricCountsHourlyParams interface.
 */
export function instanceOfListMetricCountsHourlyParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListMetricCountsHourlyParamsFromJSON(json: any): ListMetricCountsHourlyParams {
    return ListMetricCountsHourlyParamsFromJSONTyped(json, false);
}

export function ListMetricCountsHourlyParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMetricCountsHourlyParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': !exists(json, 'company_id') ? undefined : json['company_id'],
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'eventSubtype': !exists(json, 'event_subtype') ? undefined : json['event_subtype'],
        'eventSubtypes': !exists(json, 'event_subtypes') ? undefined : json['event_subtypes'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'startTime': !exists(json, 'start_time') ? undefined : (new Date(json['start_time'])),
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function ListMetricCountsHourlyParamsToJSON(value?: ListMetricCountsHourlyParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'event_subtype': value.eventSubtype,
        'event_subtypes': value.eventSubtypes,
        'limit': value.limit,
        'offset': value.offset,
        'start_time': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'user_id': value.userId,
    };
}

