/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListCompaniesParams
 */
export interface ListCompaniesParams {
    /**
     * 
     * @type {string}
     * @memberof ListCompaniesParams
     */
    dir?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ListCompaniesParams
     */
    ids?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ListCompaniesParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListCompaniesParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListCompaniesParams
     */
    order?: string;
}

/**
 * Check if a given object implements the ListCompaniesParams interface.
 */
export function instanceOfListCompaniesParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListCompaniesParamsFromJSON(json: any): ListCompaniesParams {
    return ListCompaniesParamsFromJSONTyped(json, false);
}

export function ListCompaniesParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCompaniesParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function ListCompaniesParamsToJSON(value?: ListCompaniesParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dir': value.dir,
        'ids': value.ids,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
    };
}

