/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Input parameters
 * @export
 * @interface ListApiKeysParams
 */
export interface ListApiKeysParams {
    /**
     * 
     * @type {string}
     * @memberof ListApiKeysParams
     */
    dir?: string;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeysParams
     */
    environmentId?: string;
    /**
     * 
     * @type {number}
     * @memberof ListApiKeysParams
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListApiKeysParams
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeysParams
     */
    order?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListApiKeysParams
     */
    requireEnvironment?: boolean;
}

/**
 * Check if a given object implements the ListApiKeysParams interface.
 */
export function instanceOfListApiKeysParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListApiKeysParamsFromJSON(json: any): ListApiKeysParams {
    return ListApiKeysParamsFromJSONTyped(json, false);
}

export function ListApiKeysParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeysParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
        'environmentId': !exists(json, 'environment_id') ? undefined : json['environment_id'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'requireEnvironment': !exists(json, 'require_environment') ? undefined : json['require_environment'],
    };
}

export function ListApiKeysParamsToJSON(value?: ListApiKeysParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dir': value.dir,
        'environment_id': value.environmentId,
        'limit': value.limit,
        'offset': value.offset,
        'order': value.order,
        'require_environment': value.requireEnvironment,
    };
}

