/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompanyMembershipDetailResponseData } from './CompanyMembershipDetailResponseData';
import {
    CompanyMembershipDetailResponseDataFromJSON,
    CompanyMembershipDetailResponseDataFromJSONTyped,
    CompanyMembershipDetailResponseDataToJSON,
} from './CompanyMembershipDetailResponseData';
import type { ListCompanyMembershipsParams } from './ListCompanyMembershipsParams';
import {
    ListCompanyMembershipsParamsFromJSON,
    ListCompanyMembershipsParamsFromJSONTyped,
    ListCompanyMembershipsParamsToJSON,
} from './ListCompanyMembershipsParams';

/**
 * 
 * @export
 * @interface ListCompanyMembershipsResponse
 */
export interface ListCompanyMembershipsResponse {
    /**
     * The returned resources
     * @type {Array<CompanyMembershipDetailResponseData>}
     * @memberof ListCompanyMembershipsResponse
     */
    data: Array<CompanyMembershipDetailResponseData>;
    /**
     * 
     * @type {ListCompanyMembershipsParams}
     * @memberof ListCompanyMembershipsResponse
     */
    params: ListCompanyMembershipsParams;
}

/**
 * Check if a given object implements the ListCompanyMembershipsResponse interface.
 */
export function instanceOfListCompanyMembershipsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function ListCompanyMembershipsResponseFromJSON(json: any): ListCompanyMembershipsResponse {
    return ListCompanyMembershipsResponseFromJSONTyped(json, false);
}

export function ListCompanyMembershipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCompanyMembershipsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CompanyMembershipDetailResponseDataFromJSON)),
        'params': ListCompanyMembershipsParamsFromJSON(json['params']),
    };
}

export function ListCompanyMembershipsResponseToJSON(value?: ListCompanyMembershipsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CompanyMembershipDetailResponseDataToJSON)),
        'params': ListCompanyMembershipsParamsToJSON(value.params),
    };
}

