/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventSummaryResponseData } from './EventSummaryResponseData';
import {
    EventSummaryResponseDataFromJSON,
    EventSummaryResponseDataFromJSONTyped,
    EventSummaryResponseDataToJSON,
} from './EventSummaryResponseData';
import type { ListEventTypesParams } from './ListEventTypesParams';
import {
    ListEventTypesParamsFromJSON,
    ListEventTypesParamsFromJSONTyped,
    ListEventTypesParamsToJSON,
} from './ListEventTypesParams';

/**
 * 
 * @export
 * @interface ListEventTypesResponse
 */
export interface ListEventTypesResponse {
    /**
     * The returned resources
     * @type {Array<EventSummaryResponseData>}
     * @memberof ListEventTypesResponse
     */
    data: Array<EventSummaryResponseData>;
    /**
     * 
     * @type {ListEventTypesParams}
     * @memberof ListEventTypesResponse
     */
    params: ListEventTypesParams;
}

/**
 * Check if a given object implements the ListEventTypesResponse interface.
 */
export function instanceOfListEventTypesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function ListEventTypesResponseFromJSON(json: any): ListEventTypesResponse {
    return ListEventTypesResponseFromJSONTyped(json, false);
}

export function ListEventTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEventTypesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EventSummaryResponseDataFromJSON)),
        'params': ListEventTypesParamsFromJSON(json['params']),
    };
}

export function ListEventTypesResponseToJSON(value?: ListEventTypesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(EventSummaryResponseDataToJSON)),
        'params': ListEventTypesParamsToJSON(value.params),
    };
}

