/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The created resource
 * @export
 * @interface RawEventResponseData
 */
export interface RawEventResponseData {
    /**
     * 
     * @type {Date}
     * @memberof RawEventResponseData
     */
    capturedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RawEventResponseData
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof RawEventResponseData
     */
    remoteAddr: string;
    /**
     * 
     * @type {string}
     * @memberof RawEventResponseData
     */
    remoteIp: string;
    /**
     * 
     * @type {string}
     * @memberof RawEventResponseData
     */
    userAgent: string;
}

/**
 * Check if a given object implements the RawEventResponseData interface.
 */
export function instanceOfRawEventResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "capturedAt" in value;
    isInstance = isInstance && "event" in value;
    isInstance = isInstance && "remoteAddr" in value;
    isInstance = isInstance && "remoteIp" in value;
    isInstance = isInstance && "userAgent" in value;

    return isInstance;
}

export function RawEventResponseDataFromJSON(json: any): RawEventResponseData {
    return RawEventResponseDataFromJSONTyped(json, false);
}

export function RawEventResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawEventResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capturedAt': (new Date(json['captured_at'])),
        'event': json['event'],
        'remoteAddr': json['remote_addr'],
        'remoteIp': json['remote_ip'],
        'userAgent': json['user_agent'],
    };
}

export function RawEventResponseDataToJSON(value?: RawEventResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'captured_at': (value.capturedAt.toISOString()),
        'event': value.event,
        'remote_addr': value.remoteAddr,
        'remote_ip': value.remoteIp,
        'user_agent': value.userAgent,
    };
}

