/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureDetailResponseData } from './FeatureDetailResponseData';
import {
    FeatureDetailResponseDataFromJSON,
    FeatureDetailResponseDataFromJSONTyped,
    FeatureDetailResponseDataToJSON,
} from './FeatureDetailResponseData';

/**
 * 
 * @export
 * @interface UpdateFeatureResponse
 */
export interface UpdateFeatureResponse {
    /**
     * 
     * @type {FeatureDetailResponseData}
     * @memberof UpdateFeatureResponse
     */
    data: FeatureDetailResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof UpdateFeatureResponse
     */
    params: object;
}

/**
 * Check if a given object implements the UpdateFeatureResponse interface.
 */
export function instanceOfUpdateFeatureResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function UpdateFeatureResponseFromJSON(json: any): UpdateFeatureResponse {
    return UpdateFeatureResponseFromJSONTyped(json, false);
}

export function UpdateFeatureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFeatureResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': FeatureDetailResponseDataFromJSON(json['data']),
        'params': json['params'],
    };
}

export function UpdateFeatureResponseToJSON(value?: UpdateFeatureResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': FeatureDetailResponseDataToJSON(value.data),
        'params': value.params,
    };
}

