/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureDetailResponseData } from './FeatureDetailResponseData';
import {
    FeatureDetailResponseDataFromJSON,
    FeatureDetailResponseDataFromJSONTyped,
    FeatureDetailResponseDataToJSON,
} from './FeatureDetailResponseData';

/**
 * 
 * @export
 * @interface UpdateFeatureResponse
 */
export interface UpdateFeatureResponse {
    /**
     * 
     * @type {FeatureDetailResponseData}
     * @memberof UpdateFeatureResponse
     */
    data: FeatureDetailResponseData;
    /**
     * Input parameters
     * @type {object}
     * @memberof UpdateFeatureResponse
     */
    params: object;
}

/**
 * Check if a given object implements the UpdateFeatureResponse interface.
 */
export function instanceOfUpdateFeatureResponse(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('params' in value)) return false;
    return true;
}

export function UpdateFeatureResponseFromJSON(json: any): UpdateFeatureResponse {
    return UpdateFeatureResponseFromJSONTyped(json, false);
}

export function UpdateFeatureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFeatureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': FeatureDetailResponseDataFromJSON(json['data']),
        'params': json['params'],
    };
}

export function UpdateFeatureResponseToJSON(value?: UpdateFeatureResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': FeatureDetailResponseDataToJSON(value['data']),
        'params': value['params'],
    };
}

