/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReqCommon
 */
export interface UpdateReqCommon {
    /**
     * 
     * @type {string}
     * @memberof UpdateReqCommon
     */
    metricPeriod?: UpdateReqCommonMetricPeriodEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateReqCommon
     */
    valueBool?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateReqCommon
     */
    valueNumeric?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateReqCommon
     */
    valueTraitId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReqCommon
     */
    valueType: UpdateReqCommonValueTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum UpdateReqCommonMetricPeriodEnum {
    Month = 'current_month',
    Week = 'current_week',
    Day = 'current_day'
}
/**
* @export
* @enum {string}
*/
export enum UpdateReqCommonValueTypeEnum {
    Boolean = 'Boolean',
    Numeric = 'Numeric',
    Trait = 'Trait',
    Unlimited = 'Unlimited'
}


/**
 * Check if a given object implements the UpdateReqCommon interface.
 */
export function instanceOfUpdateReqCommon(value: object): boolean {
    if (!('valueType' in value)) return false;
    return true;
}

export function UpdateReqCommonFromJSON(json: any): UpdateReqCommon {
    return UpdateReqCommonFromJSONTyped(json, false);
}

export function UpdateReqCommonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReqCommon {
    if (json == null) {
        return json;
    }
    return {
        
        'metricPeriod': json['metric_period'] == null ? undefined : json['metric_period'],
        'valueBool': json['value_bool'] == null ? undefined : json['value_bool'],
        'valueNumeric': json['value_numeric'] == null ? undefined : json['value_numeric'],
        'valueTraitId': json['value_trait_id'] == null ? undefined : json['value_trait_id'],
        'valueType': json['value_type'],
    };
}

export function UpdateReqCommonToJSON(value?: UpdateReqCommon | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metric_period': value['metricPeriod'],
        'value_bool': value['valueBool'],
        'value_numeric': value['valueNumeric'],
        'value_trait_id': value['valueTraitId'],
        'value_type': value['valueType'],
    };
}

