/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertTraitRequestBody
 */
export interface UpsertTraitRequestBody {
    /**
     * Amount to increment the trait by (positive or negative)
     * @type {number}
     * @memberof UpsertTraitRequestBody
     */
    incr?: number;
    /**
     * Key/value pairs too identify a company or user
     * @type {object}
     * @memberof UpsertTraitRequestBody
     */
    keys: object;
    /**
     * Value to set the trait to
     * @type {string}
     * @memberof UpsertTraitRequestBody
     */
    set?: string;
    /**
     * Name of the trait to update
     * @type {string}
     * @memberof UpsertTraitRequestBody
     */
    trait: string;
    /**
     * Unless this is set, the company or user will be created if it does not already exist
     * @type {boolean}
     * @memberof UpsertTraitRequestBody
     */
    updateOnly?: boolean;
}

/**
 * Check if a given object implements the UpsertTraitRequestBody interface.
 */
export function instanceOfUpsertTraitRequestBody(value: object): boolean {
    if (!('keys' in value)) return false;
    if (!('trait' in value)) return false;
    return true;
}

export function UpsertTraitRequestBodyFromJSON(json: any): UpsertTraitRequestBody {
    return UpsertTraitRequestBodyFromJSONTyped(json, false);
}

export function UpsertTraitRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertTraitRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'incr': json['incr'] == null ? undefined : json['incr'],
        'keys': json['keys'],
        'set': json['set'] == null ? undefined : json['set'],
        'trait': json['trait'],
        'updateOnly': json['update_only'] == null ? undefined : json['update_only'],
    };
}

export function UpsertTraitRequestBodyToJSON(value?: UpsertTraitRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'incr': value['incr'],
        'keys': value['keys'],
        'set': value['set'],
        'trait': value['trait'],
        'update_only': value['updateOnly'],
    };
}

