/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CRMProductResponseData } from "./CRMProductResponseData";
import {
  CRMProductResponseDataFromJSON,
  CRMProductResponseDataFromJSONTyped,
  CRMProductResponseDataToJSON,
} from "./CRMProductResponseData";

/**
 *
 * @export
 * @interface UpsertCRMProductResponse
 */
export interface UpsertCRMProductResponse {
  /**
   *
   * @type {CRMProductResponseData}
   * @memberof UpsertCRMProductResponse
   */
  data: CRMProductResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpsertCRMProductResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpsertCRMProductResponse interface.
 */
export function instanceOfUpsertCRMProductResponse(value: object): boolean {
  if (!("data" in value)) return false;
  if (!("params" in value)) return false;
  return true;
}

export function UpsertCRMProductResponseFromJSON(
  json: any,
): UpsertCRMProductResponse {
  return UpsertCRMProductResponseFromJSONTyped(json, false);
}

export function UpsertCRMProductResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertCRMProductResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CRMProductResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpsertCRMProductResponseToJSON(
  value?: UpsertCRMProductResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    data: CRMProductResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
