/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseData
 */
export interface UserResponseData {
    /**
     * 
     * @type {Date}
     * @memberof UserResponseData
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserResponseData
     */
    environmentId: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseData
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof UserResponseData
     */
    lastSeenAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseData
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof UserResponseData
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserResponseData interface.
 */
export function instanceOfUserResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "environmentId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function UserResponseDataFromJSON(json: any): UserResponseData {
    return UserResponseDataFromJSONTyped(json, false);
}

export function UserResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'environmentId': json['environment_id'],
        'id': json['id'],
        'lastSeenAt': !exists(json, 'last_seen_at') ? undefined : (json['last_seen_at'] === null ? null : new Date(json['last_seen_at'])),
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UserResponseDataToJSON(value?: UserResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.createdAt.toISOString()),
        'environment_id': value.environmentId,
        'id': value.id,
        'last_seen_at': value.lastSeenAt === undefined ? undefined : (value.lastSeenAt === null ? null : value.lastSeenAt.toISOString()),
        'name': value.name,
        'updated_at': (value.updatedAt.toISOString()),
    };
}

