/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The updated resource
 * @export
 * @interface WebhookResponseData
 */
export interface WebhookResponseData {
  /**
   *
   * @type {Date}
   * @memberof WebhookResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof WebhookResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof WebhookResponseData
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof WebhookResponseData
   */
  requestTypes: Array<string>;
  /**
   *
   * @type {string}
   * @memberof WebhookResponseData
   */
  status: string;
  /**
   *
   * @type {Date}
   * @memberof WebhookResponseData
   */
  updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof WebhookResponseData
   */
  url: string;
}

/**
 * Check if a given object implements the WebhookResponseData interface.
 */
export function instanceOfWebhookResponseData(value: object): boolean {
  if (!("createdAt" in value)) return false;
  if (!("id" in value)) return false;
  if (!("name" in value)) return false;
  if (!("requestTypes" in value)) return false;
  if (!("status" in value)) return false;
  if (!("updatedAt" in value)) return false;
  if (!("url" in value)) return false;
  return true;
}

export function WebhookResponseDataFromJSON(json: any): WebhookResponseData {
  return WebhookResponseDataFromJSONTyped(json, false);
}

export function WebhookResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookResponseData {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    name: json["name"],
    requestTypes: json["request_types"],
    status: json["status"],
    updatedAt: new Date(json["updated_at"]),
    url: json["url"],
  };
}

export function WebhookResponseDataToJSON(
  value?: WebhookResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    name: value["name"],
    request_types: value["requestTypes"],
    status: value["status"],
    updated_at: value["updatedAt"].toISOString(),
    url: value["url"],
  };
}
