name: Main

on:
  push:
    branches:
      - main

jobs:
  publish_github:
    name: Publish to Github
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@schematichq'
      - name: Set up .npmrc for private publish
        run: touch .npmrc && echo "//npm.pkg.github.com/:_authToken=$AUTH_TOKEN" > .npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Check build directory
        run: ls -al ./dist/
      - name: Publish
        uses: borales/actions-yarn@v4
        with:
          cmd: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.CH_PERSONAL_ACCESS_TOKEN }}

  publish_npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: ["test", "lint"]
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Set up .npmrc
        run: touch .npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn publish --access public

  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: [publish_npm, publish_github]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Updated schematic-typescript-node
          SLACK_ICON: https://schematic-public-assets.s3.amazonaws.com/logos/logo-transparent.png
